#:schema node_modules/wrangler/config-schema.json
name = "healthyweb"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

send_metrics = false

# Docs: https://developers.cloudflare.com/workers/configuration/environment-variables/
[vars]
LATEST_JQUERY_VERSION = "4.0.0"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/bindings/service-bindings/
[[services]]
binding = "HEALTHYWEB_WORKER"
service = "healthyweb-worker"
